#!/usr/bin/php
<?php

require_once('vendor/autoload.php');
use StephenHill\Base58;

$bits = 32;
if (isset($argv[1]) === true)
{
    if (ctype_digit($argv[1]) === true)
    {
        $bits = (int)$argv[1];
    }
}

$b = new Base58();
$p = $b->encode(openssl_random_pseudo_bytes($bits));

echo $p . PHP_EOL;
